/** Vocabulary for ~3rd grade: short words, clear themes, fun emoji cues */

export const categories = [
  {
    id: "animals",
    title: "Звери",
    titleEn: "Animals",
    emoji: "🦁",
    color: "#2bb673",
    words: [
      { en: "cat", ru: "кот", emoji: "🐱", hint: "мяукает" },
      { en: "dog", ru: "собака", emoji: "🐶", hint: "гавкает" },
      { en: "bird", ru: "птица", emoji: "🐦", hint: "летает" },
      { en: "fish", ru: "рыба", emoji: "🐟", hint: "плавает" },
      { en: "lion", ru: "лев", emoji: "🦁", hint: "царь зверей" },
      { en: "bear", ru: "медведь", emoji: "🐻", hint: "любит мёд" },
      { en: "frog", ru: "лягушка", emoji: "🐸", hint: "квакает" },
      { en: "horse", ru: "лошадь", emoji: "🐴", hint: "скачет" },
      { en: "mouse", ru: "мышь", emoji: "🐭", hint: "очень маленькая" },
      { en: "cow", ru: "корова", emoji: "🐮", hint: "даёт молоко" },
      { en: "pig", ru: "свинья", emoji: "🐷", hint: "хрюкает" },
      { en: "duck", ru: "утка", emoji: "🦆", hint: "крякает" },
      { en: "rabbit", ru: "кролик", emoji: "🐰", hint: "длинные уши" },
      { en: "fox", ru: "лиса", emoji: "🦊", hint: "рыжая" },
      { en: "wolf", ru: "волк", emoji: "🐺", hint: "серый и дикий" },
      { en: "monkey", ru: "обезьяна", emoji: "🐵", hint: "любит бананы" },
      { en: "tiger", ru: "тигр", emoji: "🐯", hint: "в полоску" },
      { en: "elephant", ru: "слон", emoji: "🐘", hint: "с хоботом" },
      { en: "giraffe", ru: "жираф", emoji: "🦒", hint: "длинная шея" },
      { en: "snake", ru: "змея", emoji: "🐍", hint: "ползает" },
      { en: "bee", ru: "пчела", emoji: "🐝", hint: "делает мёд" },
      { en: "butterfly", ru: "бабочка", emoji: "🦋", hint: "красивые крылья" },
      { en: "turtle", ru: "черепаха", emoji: "🐢", hint: "медленно ходит" },
      { en: "owl", ru: "сова", emoji: "🦉", hint: "не спит ночью" },
    ],
  },
  {
    id: "colors",
    title: "Цвета",
    titleEn: "Colors",
    emoji: "🎨",
    color: "#e85d4c",
    words: [
      { en: "red", ru: "красный", emoji: "🔴", hint: "как яблоко" },
      { en: "blue", ru: "синий", emoji: "🔵", hint: "как небо" },
      { en: "green", ru: "зелёный", emoji: "🟢", hint: "как трава" },
      { en: "yellow", ru: "жёлтый", emoji: "🟡", hint: "как солнце" },
      { en: "orange", ru: "оранжевый", emoji: "🟠", hint: "как апельсин" },
      { en: "purple", ru: "фиолетовый", emoji: "🟣", hint: "как виноград" },
      { en: "black", ru: "чёрный", emoji: "⚫", hint: "как ночь" },
      { en: "white", ru: "белый", emoji: "⚪", hint: "как снег" },
      { en: "pink", ru: "розовый", emoji: "💗", hint: "как фламинго" },
      { en: "brown", ru: "коричневый", emoji: "🤎", hint: "как шоколад" },
      { en: "grey", ru: "серый", emoji: "🩶", hint: "как туча" },
      { en: "gold", ru: "золотой", emoji: "🥇", hint: "как медаль" },
      { en: "silver", ru: "серебряный", emoji: "🥈", hint: "блестит" },
      { en: "big", ru: "большой", emoji: "🐘", hint: "не маленький" },
      { en: "small", ru: "маленький", emoji: "🐭", hint: "небольшой" },
      { en: "bright", ru: "яркий", emoji: "✨", hint: "очень заметный" },
      { en: "rainbow", ru: "радуга", emoji: "🌈", hint: "много цветов сразу" },
      { en: "color", ru: "цвет", emoji: "🎨", hint: "красный, синий..." },
      { en: "paint", ru: "краска", emoji: "🖌️", hint: "рисуем ею" },
      { en: "sky", ru: "небо", emoji: "☁️", hint: "над нами" },
      { en: "grass", ru: "трава", emoji: "🌱", hint: "зелёная" },
      { en: "snow", ru: "снег", emoji: "❄️", hint: "зимой белый" },
      { en: "sun", ru: "солнце", emoji: "☀️", hint: "жёлтое и тёплое" },
      { en: "night", ru: "ночь", emoji: "🌙", hint: "когда темно" },
    ],
  },
  {
    id: "food",
    title: "Еда",
    titleEn: "Food",
    emoji: "🍎",
    color: "#f0a202",
    words: [
      { en: "apple", ru: "яблоко", emoji: "🍎", hint: "красное или зелёное" },
      { en: "banana", ru: "банан", emoji: "🍌", hint: "жёлтый и длинный" },
      { en: "bread", ru: "хлеб", emoji: "🍞", hint: "на завтрак" },
      { en: "milk", ru: "молоко", emoji: "🥛", hint: "белое питьё" },
      { en: "cheese", ru: "сыр", emoji: "🧀", hint: "жёлтый кусочек" },
      { en: "cake", ru: "торт", emoji: "🎂", hint: "на день рождения" },
      { en: "pizza", ru: "пицца", emoji: "🍕", hint: "с сыром" },
      { en: "water", ru: "вода", emoji: "💧", hint: "важно пить" },
      { en: "egg", ru: "яйцо", emoji: "🥚", hint: "на завтрак" },
      { en: "rice", ru: "рис", emoji: "🍚", hint: "белый гарнир" },
      { en: "soup", ru: "суп", emoji: "🍲", hint: "едят ложкой" },
      { en: "meat", ru: "мясо", emoji: "🥩", hint: "на второе" },
      { en: "fish", ru: "рыба", emoji: "🐟", hint: "из моря" },
      { en: "juice", ru: "сок", emoji: "🧃", hint: "из фруктов" },
      { en: "tea", ru: "чай", emoji: "🍵", hint: "горячий напиток" },
      { en: "coffee", ru: "кофе", emoji: "☕", hint: "для взрослых" },
      { en: "candy", ru: "конфета", emoji: "🍬", hint: "сладкая" },
      { en: "cookie", ru: "печенье", emoji: "🍪", hint: "хрустит" },
      { en: "orange", ru: "апельсин", emoji: "🍊", hint: "оранжевый фрукт" },
      { en: "grape", ru: "виноград", emoji: "🍇", hint: "маленькие ягодки" },
      { en: "carrot", ru: "морковь", emoji: "🥕", hint: "оранжевый овощ" },
      { en: "tomato", ru: "помидор", emoji: "🍅", hint: "красный овощ" },
      { en: "potato", ru: "картошка", emoji: "🥔", hint: "из неё пюре" },
      { en: "salad", ru: "салат", emoji: "🥗", hint: "свежие овощи" },
    ],
  },
  {
    id: "school",
    title: "Школа",
    titleEn: "School",
    emoji: "📚",
    color: "#3d8bfd",
    words: [
      { en: "book", ru: "книга", emoji: "📖", hint: "читаем её" },
      { en: "pen", ru: "ручка", emoji: "🖊️", hint: "пишем ею" },
      { en: "bag", ru: "сумка", emoji: "🎒", hint: "носим в школу" },
      { en: "desk", ru: "парта", emoji: "🪑", hint: "за ней сидим" },
      { en: "teacher", ru: "учитель", emoji: "👩‍🏫", hint: "ведёт урок" },
      { en: "friend", ru: "друг", emoji: "🤝", hint: "рядом в классе" },
      { en: "school", ru: "школа", emoji: "🏫", hint: "учимся здесь" },
      { en: "ruler", ru: "линейка", emoji: "📏", hint: "чертим линии" },
      { en: "pencil", ru: "карандаш", emoji: "✏️", hint: "можно стереть" },
      { en: "eraser", ru: "ластик", emoji: "🧽", hint: "стирает ошибки" },
      { en: "paper", ru: "бумага", emoji: "📄", hint: "на ней пишем" },
      { en: "notebook", ru: "тетрадь", emoji: "📓", hint: "для уроков" },
      { en: "class", ru: "класс", emoji: "🧑‍🤝‍🧑", hint: "ученики вместе" },
      { en: "lesson", ru: "урок", emoji: "🗓️", hint: "время учиться" },
      { en: "board", ru: "доска", emoji: "📋", hint: "учитель пишет" },
      { en: "map", ru: "карта", emoji: "🗺️", hint: "страны и моря" },
      { en: "globe", ru: "глобус", emoji: "🌍", hint: "круглая Земля" },
      { en: "test", ru: "тест", emoji: "✅", hint: "проверяют знания" },
      { en: "homework", ru: "домашка", emoji: "📝", hint: "делаем дома" },
      { en: "library", ru: "библиотека", emoji: "📚", hint: "много книг" },
      { en: "bell", ru: "звонок", emoji: "🔔", hint: "на урок и перемену" },
      { en: "break", ru: "перемена", emoji: "⏱️", hint: "время отдохнуть" },
      { en: "pupil", ru: "ученик", emoji: "🧒", hint: "учится в школе" },
      { en: "crayon", ru: "восковой карандаш", emoji: "🖍️", hint: "рисуем цветным" },
      { en: "ball", ru: "мяч", emoji: "⚽", hint: "круглый, для игры" },
    ],
  },
  {
    id: "home",
    title: "Дом",
    titleEn: "Home",
    emoji: "🏠",
    color: "#9b59b6",
    words: [
      { en: "house", ru: "дом", emoji: "🏠", hint: "где живём" },
      { en: "door", ru: "дверь", emoji: "🚪", hint: "открываем её" },
      { en: "window", ru: "окно", emoji: "🪟", hint: "смотрим наружу" },
      { en: "bed", ru: "кровать", emoji: "🛏️", hint: "спим на ней" },
      { en: "table", ru: "стол", emoji: "🪵", hint: "едим за ним" },
      { en: "chair", ru: "стул", emoji: "🪑", hint: "сидим на нём" },
      { en: "lamp", ru: "лампа", emoji: "💡", hint: "светит вечером" },
      { en: "clock", ru: "часы", emoji: "🕐", hint: "показывают время" },
      { en: "room", ru: "комната", emoji: "🛋️", hint: "часть дома" },
      { en: "kitchen", ru: "кухня", emoji: "🍳", hint: "готовим еду" },
      { en: "bathroom", ru: "ванная", emoji: "🛁", hint: "моемся здесь" },
      { en: "garden", ru: "сад", emoji: "🌳", hint: "растения во дворе" },
      { en: "floor", ru: "пол", emoji: "🟫", hint: "под ногами" },
      { en: "wall", ru: "стена", emoji: "🧱", hint: "рядом с нами" },
      { en: "roof", ru: "крыша", emoji: "🏘️", hint: "верх дома" },
      { en: "key", ru: "ключ", emoji: "🔑", hint: "открывает дверь" },
      { en: "sofa", ru: "диван", emoji: "🛋️", hint: "мягкий и длинный" },
      { en: "mirror", ru: "зеркало", emoji: "🪞", hint: "видим себя" },
      { en: "cup", ru: "чашка", emoji: "☕", hint: "пьём из неё" },
      { en: "plate", ru: "тарелка", emoji: "🍽️", hint: "еда на ней" },
      { en: "spoon", ru: "ложка", emoji: "🥄", hint: "для супа" },
      { en: "fork", ru: "вилка", emoji: "🍴", hint: "с зубчиками" },
      { en: "phone", ru: "телефон", emoji: "📱", hint: "звоним друзьям" },
      { en: "TV", ru: "телевизор", emoji: "📺", hint: "смотрим мультики" },
    ],
  },
  {
    id: "actions",
    title: "Действия",
    titleEn: "Actions",
    emoji: "🏃",
    color: "#00a8a8",
    words: [
      { en: "run", ru: "бегать", emoji: "🏃", hint: "быстро ногами" },
      { en: "jump", ru: "прыгать", emoji: "🦘", hint: "вверх!" },
      { en: "swim", ru: "плавать", emoji: "🏊", hint: "в воде" },
      { en: "read", ru: "читать", emoji: "📚", hint: "книги" },
      { en: "write", ru: "писать", emoji: "✍️", hint: "буквы" },
      { en: "sing", ru: "петь", emoji: "🎤", hint: "песни" },
      { en: "play", ru: "играть", emoji: "🎮", hint: "весело" },
      { en: "sleep", ru: "спать", emoji: "😴", hint: "ночью" },
      { en: "eat", ru: "есть", emoji: "🍽️", hint: "когда голоден" },
      { en: "drink", ru: "пить", emoji: "🥤", hint: "когда хочешь пить" },
      { en: "walk", ru: "ходить", emoji: "🚶", hint: "шагами" },
      { en: "dance", ru: "танцевать", emoji: "💃", hint: "под музыку" },
      { en: "draw", ru: "рисовать", emoji: "🎨", hint: "картинки" },
      { en: "cook", ru: "готовить", emoji: "👨‍🍳", hint: "на кухне" },
      { en: "listen", ru: "слушать", emoji: "👂", hint: "ушами" },
      { en: "look", ru: "смотреть", emoji: "👀", hint: "глазами" },
      { en: "open", ru: "открывать", emoji: "📂", hint: "дверь или книгу" },
      { en: "close", ru: "закрывать", emoji: "🚪", hint: "наоборот от open" },
      { en: "sit", ru: "сидеть", emoji: "🪑", hint: "на стуле" },
      { en: "stand", ru: "стоять", emoji: "🧍", hint: "на ногах" },
      { en: "smile", ru: "улыбаться", emoji: "😊", hint: "когда радостно" },
      { en: "help", ru: "помогать", emoji: "🆘", hint: "другу" },
      { en: "clean", ru: "убирать", emoji: "🧹", hint: "дома" },
      { en: "learn", ru: "учиться", emoji: "🧠", hint: "узнавать новое" },
      { en: "go", ru: "идти", emoji: "➡️", hint: "направляться" },
      { en: "see", ru: "видеть", emoji: "👁️", hint: "глазами" },
      { en: "like", ru: "нравиться", emoji: "👍", hint: "любить что-то" },
      { en: "want", ru: "хотеть", emoji: "🙏", hint: "желание" },
    ],
  },
  {
    id: "numbers",
    title: "Числа",
    titleEn: "Numbers",
    emoji: "🔢",
    color: "#ff6b6b",
    words: [
      { en: "zero", ru: "ноль", emoji: "0️⃣", hint: "ничего, пусто" },
      { en: "one", ru: "один", emoji: "1️⃣", hint: "самое маленькое после нуля" },
      { en: "two", ru: "два", emoji: "2️⃣", hint: "пара" },
      { en: "three", ru: "три", emoji: "3️⃣", hint: "как колёса у трёхколёски" },
      { en: "four", ru: "четыре", emoji: "4️⃣", hint: "ноги у стола" },
      { en: "five", ru: "пять", emoji: "5️⃣", hint: "пальцы на руке" },
      { en: "six", ru: "шесть", emoji: "6️⃣", hint: "после пяти" },
      { en: "seven", ru: "семь", emoji: "7️⃣", hint: "дней в неделе" },
      { en: "eight", ru: "восемь", emoji: "8️⃣", hint: "как снеговик" },
      { en: "nine", ru: "девять", emoji: "9️⃣", hint: "перед десятью" },
      { en: "ten", ru: "десять", emoji: "🔟", hint: "все пальцы рук" },
      { en: "eleven", ru: "одиннадцать", emoji: "🔢", hint: "десять плюс один" },
      { en: "twelve", ru: "двенадцать", emoji: "🕛", hint: "часов на циферблате" },
      { en: "thirteen", ru: "тринадцать", emoji: "🔢", hint: "десять плюс три" },
      { en: "fourteen", ru: "четырнадцать", emoji: "🔢", hint: "десять плюс четыре" },
      { en: "fifteen", ru: "пятнадцать", emoji: "🔢", hint: "десять плюс пять" },
      { en: "sixteen", ru: "шестнадцать", emoji: "🔢", hint: "десять плюс шесть" },
      { en: "twenty", ru: "двадцать", emoji: "🔢", hint: "два десятка" },
      { en: "thirty", ru: "тридцать", emoji: "🔢", hint: "три десятка" },
      { en: "fifty", ru: "пятьдесят", emoji: "🔢", hint: "пять десятков" },
      { en: "hundred", ru: "сто", emoji: "💯", hint: "десять десятков" },
      { en: "number", ru: "число", emoji: "🔢", hint: "один, два, три…" },
      { en: "plus", ru: "плюс", emoji: "➕", hint: "складываем" },
      { en: "count", ru: "считать", emoji: "🧮", hint: "один, два, три" },
    ],
  },
  {
    id: "family",
    title: "Семья",
    titleEn: "Family",
    emoji: "👨‍👩‍👧",
    color: "#e17055",
    words: [
      { en: "mum", ru: "мама", emoji: "👩", hint: "мама" },
      { en: "dad", ru: "папа", emoji: "👨", hint: "папа" },
      { en: "sister", ru: "сестра", emoji: "👧", hint: "девочка в семье" },
      { en: "brother", ru: "брат", emoji: "👦", hint: "мальчик в семье" },
      { en: "baby", ru: "малыш", emoji: "👶", hint: "совсем маленький" },
      { en: "grandma", ru: "бабушка", emoji: "👵", hint: "мама мамы" },
      { en: "grandpa", ru: "дедушка", emoji: "👴", hint: "папа папы" },
      { en: "family", ru: "семья", emoji: "👨‍👩‍👧", hint: "все вместе" },
      { en: "aunt", ru: "тётя", emoji: "👩‍🦰", hint: "сестра мамы" },
      { en: "uncle", ru: "дядя", emoji: "👨‍🦰", hint: "брат папы" },
      { en: "cousin", ru: "двоюр. брат/сестра", emoji: "🧒", hint: "ребёнок тёти или дяди" },
      { en: "boy", ru: "мальчик", emoji: "👦", hint: "он" },
      { en: "girl", ru: "девочка", emoji: "👧", hint: "она" },
      { en: "man", ru: "мужчина", emoji: "👨", hint: "взрослый он" },
      { en: "woman", ru: "женщина", emoji: "👩", hint: "взрослая она" },
      { en: "child", ru: "ребёнок", emoji: "🧒", hint: "не взрослый" },
      { en: "friend", ru: "друг", emoji: "🤗", hint: "не семья, но рядом" },
      { en: "name", ru: "имя", emoji: "🏷️", hint: "как тебя зовут" },
      { en: "love", ru: "любить", emoji: "❤️", hint: "семью и друзей" },
      { en: "hug", ru: "обнимать", emoji: "🫂", hint: "крепко обнять" },
      { en: "home", ru: "дом", emoji: "🏡", hint: "где семья" },
      { en: "pet", ru: "питомец", emoji: "🐾", hint: "кот или собака" },
      { en: "people", ru: "люди", emoji: "👥", hint: "много человек" },
      { en: "happy", ru: "счастливый", emoji: "😄", hint: "весело и хорошо" },
    ],
  },
  {
    id: "clothes",
    title: "Одежда",
    titleEn: "Clothes",
    emoji: "👕",
    color: "#6c5ce7",
    words: [
      { en: "hat", ru: "шляпа", emoji: "🎩", hint: "на голове" },
      { en: "cap", ru: "кепка", emoji: "🧢", hint: "с козырьком" },
      { en: "shirt", ru: "рубашка", emoji: "👔", hint: "с пуговицами" },
      { en: "top", ru: "топ", emoji: "👕", hint: "лёгкая футболка" },
      { en: "dress", ru: "платье", emoji: "👗", hint: "для девочек" },
      { en: "skirt", ru: "юбка", emoji: "👗", hint: "вместо брюк" },
      { en: "pants", ru: "штаны", emoji: "👖", hint: "на ногах" },
      { en: "jeans", ru: "джинсы", emoji: "👖", hint: "синие штаны" },
      { en: "socks", ru: "носки", emoji: "🧦", hint: "на ступнях" },
      { en: "shoes", ru: "обувь", emoji: "👟", hint: "ходим в ней" },
      { en: "boots", ru: "сапоги", emoji: "🥾", hint: "высокие" },
      { en: "coat", ru: "пальто", emoji: "🧥", hint: "зимой на улице" },
      { en: "jacket", ru: "куртка", emoji: "🧥", hint: "на молнии" },
      { en: "scarf", ru: "шарф", emoji: "🧣", hint: "на шее" },
      { en: "gloves", ru: "перчатки", emoji: "🧤", hint: "на руках" },
      { en: "sweater", ru: "свитер", emoji: "🧶", hint: "тёплый" },
      { en: "shorts", ru: "шорты", emoji: "🩳", hint: "короткие штаны" },
      { en: "umbrella", ru: "зонт", emoji: "☂️", hint: "от дождя" },
      { en: "bag", ru: "сумка", emoji: "👜", hint: "носим вещи" },
      { en: "watch", ru: "часы", emoji: "⌚", hint: "на руке" },
      { en: "glasses", ru: "очки", emoji: "👓", hint: "на носу" },
      { en: "button", ru: "пуговица", emoji: "🔘", hint: "на рубашке" },
      { en: "pocket", ru: "карман", emoji: "👖", hint: "кладём мелочи" },
      { en: "clothes", ru: "одежда", emoji: "👚", hint: "всё, что носим" },
    ],
  },
];

export const phrases = [
  {
    en: ["I", "like", "cats"],
    ru: "Я люблю кошек",
    emoji: "🐱",
    themes: ["animals"],
    options: ["I", "like", "cats", "dogs", "birds", "frogs"],
  },
  {
    en: ["I", "have", "a", "dog"],
    ru: "У меня есть собака",
    emoji: "🐶",
    themes: ["animals"],
    options: ["I", "have", "a", "dog", "cat", "fish"],
  },
  {
    en: ["It", "is", "a", "green", "frog"],
    ru: "Это зелёная лягушка",
    emoji: "🐸",
    themes: ["animals", "colors"],
    options: ["It", "is", "a", "green", "frog", "blue", "bird"],
  },
  {
    en: ["I", "see", "a", "big", "lion"],
    ru: "Я вижу большого льва",
    emoji: "🦁",
    themes: ["animals", "colors"],
    options: ["I", "see", "a", "big", "lion", "small", "fish"],
  },
  {
    en: ["The", "sun", "is", "yellow"],
    ru: "Солнце жёлтое",
    emoji: "☀️",
    themes: ["colors"],
    options: ["The", "sun", "is", "yellow", "blue", "red"],
  },
  {
    en: ["I", "want", "an", "apple"],
    ru: "Я хочу яблоко",
    emoji: "🍎",
    themes: ["food"],
    options: ["I", "want", "an", "apple", "bread", "milk"],
  },
  {
    en: ["We", "eat", "bread"],
    ru: "Мы едим хлеб",
    emoji: "🍞",
    themes: ["food", "actions"],
    options: ["We", "eat", "bread", "drink", "milk", "cake"],
  },
  {
    en: ["They", "like", "pizza"],
    ru: "Они любят пиццу",
    emoji: "🍕",
    themes: ["food"],
    options: ["They", "like", "pizza", "cake", "cheese", "soup"],
  },
  {
    en: ["I", "drink", "milk"],
    ru: "Я пью молоко",
    emoji: "🥛",
    themes: ["food", "actions"],
    options: ["I", "drink", "milk", "water", "eat", "tea"],
  },
  {
    en: ["This", "is", "a", "book"],
    ru: "Это книга",
    emoji: "📖",
    themes: ["school"],
    options: ["This", "is", "a", "book", "pen", "bag"],
  },
  {
    en: ["I", "am", "a", "pupil"],
    ru: "Я ученик",
    emoji: "🧒",
    themes: ["school"],
    options: ["I", "am", "a", "pupil", "teacher", "friend"],
  },
  {
    en: ["We", "play", "at", "school"],
    ru: "Мы играем в школе",
    emoji: "🏫",
    themes: ["school", "actions"],
    options: ["We", "play", "at", "school", "house", "desk"],
  },
  {
    en: ["I", "go", "to", "school"],
    ru: "Я иду в школу",
    emoji: "🏫",
    themes: ["school", "actions"],
    options: ["I", "go", "to", "school", "home", "class"],
  },
  {
    en: ["He", "has", "a", "red", "ball"],
    ru: "У него красный мяч",
    emoji: "⚽",
    themes: ["school", "colors"],
    options: ["He", "has", "a", "red", "ball", "blue", "bag"],
  },
  {
    en: ["Open", "the", "door"],
    ru: "Открой дверь",
    emoji: "🚪",
    themes: ["home", "actions"],
    options: ["Open", "the", "door", "window", "close", "bed"],
  },
  {
    en: ["The", "cat", "is", "on", "the", "bed"],
    ru: "Кот на кровати",
    emoji: "🐱",
    themes: ["home", "animals"],
    options: ["The", "cat", "is", "on", "the", "bed", "table", "dog"],
  },
  {
    en: ["I", "can", "swim"],
    ru: "Я умею плавать",
    emoji: "🏊",
    themes: ["actions"],
    options: ["I", "can", "swim", "jump", "run", "sing"],
  },
  {
    en: ["She", "can", "sing"],
    ru: "Она умеет петь",
    emoji: "🎤",
    themes: ["actions"],
    options: ["She", "can", "sing", "play", "read", "write"],
  },
  {
    en: ["Please", "help", "me"],
    ru: "Пожалуйста, помоги мне",
    emoji: "🆘",
    themes: ["actions"],
    options: ["Please", "help", "me", "you", "play", "learn"],
  },
  {
    en: ["I", "can", "count", "to", "ten"],
    ru: "Я умею считать до десяти",
    emoji: "🔟",
    themes: ["numbers", "actions"],
    options: ["I", "can", "count", "to", "ten", "five", "two"],
  },
  {
    en: ["She", "has", "two", "sisters"],
    ru: "У неё две сестры",
    emoji: "👧",
    themes: ["family", "numbers"],
    options: ["She", "has", "two", "sisters", "brothers", "one", "three"],
  },
  {
    en: ["My", "mum", "is", "happy"],
    ru: "Моя мама счастлива",
    emoji: "👩",
    themes: ["family"],
    options: ["My", "mum", "is", "happy", "dad", "sister"],
  },
  {
    en: ["We", "are", "happy"],
    ru: "Мы счастливы",
    emoji: "😄",
    themes: ["family"],
    options: ["We", "are", "happy", "family", "big", "girl"],
  },
  {
    en: ["I", "put", "on", "my", "hat"],
    ru: "Я надеваю шляпу",
    emoji: "🎩",
    themes: ["clothes"],
    options: ["I", "put", "on", "my", "hat", "shoes", "coat"],
  },
];

export const games = [
  {
    id: "quiz",
    title: "Угадай слово",
    desc: "Смотри картинку и выбирай английское слово",
    emoji: "🎯",
  },
  {
    id: "listen",
    title: "Слушай!",
    desc: "Услышь слово и найди правильную карточку",
    emoji: "🎧",
  },
  {
    id: "spell",
    title: "Собери слово",
    desc: "Расставь буквы в правильном порядке",
    emoji: "🔤",
  },
  {
    id: "memory",
    title: "Найди пару",
    desc: "Открывай карточки и соединяй слово с переводом",
    emoji: "🧠",
  },
  {
    id: "phrase",
    title: "Собери фразу",
    desc: "Составь простое английское предложение",
    emoji: "💬",
  },
];

export const UNLOCK_ORDER = [
  "animals",
  "colors",
  "numbers",
  "family",
  "food",
  "school",
  "home",
  "actions",
  "clothes",
];

export function getAllWords() {
  return categories.flatMap((c) =>
    c.words.map((w) => ({ ...w, categoryId: c.id, categoryColor: c.color }))
  );
}

export function getCategory(id) {
  return categories.find((c) => c.id === id);
}
